### ISSUE TITLE
Image refresh and image overlap problems

### ISSUE THREAD

**Issue by w5c17** [openseadragon/openseadragon#2594]
Hello author,I found that there is a gap between tiles, I suspect it is the Overlap attribute, but I have set it to 0, but this gap still exists, do you have any good solution
![567840ad3d32414a3438e2669243e1a](https://github.com/user-attachments/assets/0d5b247e-62cf-45b5-8e5e-0b25d84f31e8)
![肺 8小时-sug-1- _20X_20241011104954](https://github.com/user-attachments/assets/d3f71262-17cb-4238-93bc-e4f3cf0bf108)
In addition to that, I have another problem, when I open an image, I want to change the contrast and brightness of the image and so on to display a new image,`  this.viewer.open(this.setTileSource(this.headinfo, this.$props.tab.url, this.curLevel,form));`
![image](https://github.com/user-attachments/assets/b136bb1b-5727-4d26-a357-516c31352843)
I get the result through the open method every time I set the image source to request a new tile map, but this method will refresh every time, the experience is not very good, do you have any good solution，

**Comment by iangilman** [comment]
Looks like you're using the canvas drawer. It introduces a small overlap (the opposite of a gap really) to avoid seams if your image doesn't have its own overlap (you can learn more here: https://github.com/openseadragon/openseadragon/issues/1722). There are a couple of ways to fix this: 

* Upgrade to OSD 5.0.0 and use the default WebGL drawer. 
* Redo your images to have an overlap of 1.

Either of those will fix the issue; you don't need to do both.

As for swapping in a new image, you can use the technique demonstrated here: 

https://codepen.io/iangilman/pen/PjdyGv

Another option would be to modify the tiles in place without going to the server. This plugin can do that:

https://github.com/usnistgov/OpenSeadragonFiltering

**Comment by w5c17** [comment]
Thank you very much. The above two problems have been solved.But I found that with the image refresh problem, I used the technique you used in your code,Image update is obviously slow for a long time, do you know why

**Comment by iangilman** [comment]
With that technique it's waiting for the new image to be fully loaded before switching to it, so depending on your server and your network it could take a little while. You could skip waiting for the `fully-loaded-change` event, but then you'd still get a little flash. Another approach would be to load the new image ahead of time before the user asks for it. 

But if you want speed, modifying the tiles in place using the filtering plugin is best, since you don't have to wait for the server.

**Comment by w5c17** [comment]
The image I requested needs to be refreshed in real time according to the parameters, so it is not a good plan to load the new image before the user requests it. In addition, I observed that it only takes 2ms to request each Tile of the new image from the server. However, it took a total of about 1500ms after all loading. I used filter plug-in before, but we needed to save some parameters to the server and the filter plug-in could not meet our needs, so I needed to request new images from the server. Is there such a scheme, only load the image in my field of vision, do not wait until all load can update the new image
![1728954208138](https://github.com/user-attachments/assets/4c1e2ef3-ba34-4803-9605-d7cac0e81660)

**Comment by iangilman** [comment]
`fully-loaded-change` is just for the tiles in the viewable area; it's not concerned with anything not visible.

I think what's taking the time is it's loading each tile one after the next. You could try loading them in parallel and see how that goes. Use something like `maxTilesPerFrame: 50` in your viewer options and see if that helps.

**Comment by w5c17** [comment]
Thank you for your answer. After setting maxTilesPerFrame: 50, the speed is significantly faster, which is already within the acceptable range
